/* JasperServerStub.h
   Generated by gSOAP 2.8.5 from JasperServer.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef JasperServerStub_H
#define JasperServerStub_H
#include <vector>
#ifndef WITH_NONAMESPACES
#define WITH_NONAMESPACES
#endif
#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#include "stdsoap2.h"

namespace JasperServer {

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__getResponse
#define SOAP_TYPE_JasperServer_JasperServer__getResponse (11)
/* JasperServer:getResponse */
struct JasperServer__getResponse
{
public:
	std::string _getReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__get
#define SOAP_TYPE_JasperServer_JasperServer__get (12)
/* JasperServer:get */
struct JasperServer__get
{
public:
	std::string _requestXmlString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__putResponse
#define SOAP_TYPE_JasperServer_JasperServer__putResponse (14)
/* JasperServer:putResponse */
struct JasperServer__putResponse
{
public:
	std::string _putReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__put
#define SOAP_TYPE_JasperServer_JasperServer__put (15)
/* JasperServer:put */
struct JasperServer__put
{
public:
	std::string _requestXmlString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__listResponse
#define SOAP_TYPE_JasperServer_JasperServer__listResponse (17)
/* JasperServer:listResponse */
struct JasperServer__listResponse
{
public:
	std::string _listReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__list
#define SOAP_TYPE_JasperServer_JasperServer__list (18)
/* JasperServer:list */
struct JasperServer__list
{
public:
	std::string _requestXmlString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__copyResponse
#define SOAP_TYPE_JasperServer_JasperServer__copyResponse (20)
/* JasperServer:copyResponse */
struct JasperServer__copyResponse
{
public:
	std::string _copyReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__copy
#define SOAP_TYPE_JasperServer_JasperServer__copy (21)
/* JasperServer:copy */
struct JasperServer__copy
{
public:
	std::string _requestXmlString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__deleteResponse
#define SOAP_TYPE_JasperServer_JasperServer__deleteResponse (23)
/* JasperServer:deleteResponse */
struct JasperServer__deleteResponse
{
public:
	std::string _deleteReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__delete
#define SOAP_TYPE_JasperServer_JasperServer__delete (24)
/* JasperServer:delete */
struct JasperServer__delete
{
public:
	std::string _requestXmlString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__runReportResponse
#define SOAP_TYPE_JasperServer_JasperServer__runReportResponse (26)
/* JasperServer:runReportResponse */
struct JasperServer__runReportResponse
{
public:
	std::string _runReportReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__runReport
#define SOAP_TYPE_JasperServer_JasperServer__runReport (27)
/* JasperServer:runReport */
struct JasperServer__runReport
{
public:
	std::string _requestXmlString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__moveResponse
#define SOAP_TYPE_JasperServer_JasperServer__moveResponse (29)
/* JasperServer:moveResponse */
struct JasperServer__moveResponse
{
public:
	std::string _moveReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_JasperServer_JasperServer__move
#define SOAP_TYPE_JasperServer_JasperServer__move (30)
/* JasperServer:move */
struct JasperServer__move
{
public:
	std::string _requestXmlString;	/* required element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_JasperServer_SOAP_ENV__Header
#define SOAP_TYPE_JasperServer_SOAP_ENV__Header (31)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_JasperServer_SOAP_ENV__Code
#define SOAP_TYPE_JasperServer_SOAP_ENV__Code (32)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_JasperServer_SOAP_ENV__Detail
#define SOAP_TYPE_JasperServer_SOAP_ENV__Detail (34)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_JasperServer_SOAP_ENV__Reason
#define SOAP_TYPE_JasperServer_SOAP_ENV__Reason (37)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_JasperServer_SOAP_ENV__Fault
#define SOAP_TYPE_JasperServer_SOAP_ENV__Fault (38)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE_JasperServer__QName
#define SOAP_TYPE_JasperServer__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_JasperServer__XML
#define SOAP_TYPE_JasperServer__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


} // namespace JasperServer


#endif

/* End of JasperServerStub.h */
