######################################################################
# Automatically generated by qmake (2.01a) ven. juin 8 21:29:34 2007
######################################################################

include (../../../../config.pri)

TEMPLATE = lib
TARGET = qcodeedit
LIBS += -lconfig

DEPENDPATH += . document language widgets qnfa
INCLUDEPATH += . document language widgets qnfa ../../../lib/config

CONFIG += qnfa

QT += xml

# Input
include(lib.pri)
